In [1]:
# 1. ONE-HOT ENCODING

import numpy as np

sentence = "machine learning is useful"

words = sentence.lower().split()

vocabulary = sorted(set(words))

print("Vocabulary:")
print(vocabulary)

one_hot_vectors = np.eye(len(vocabulary))

print("\nOne-Hot Encodings:\n")

for word, vector in zip(vocabulary, one_hot_vectors):
    print(f"{word}: {vector}")

Vocabulary:
['is', 'learning', 'machine', 'useful']

One-Hot Encodings:

is: [1. 0. 0. 0.]
learning: [0. 1. 0. 0.]
machine: [0. 0. 1. 0.]
useful: [0. 0. 0. 1.]


In [2]:
# 2. BAG OF WORDS

from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "machine learning is useful",
    "machine learning is powerful",
    "artificial intelligence is useful"
]

vectorizer = CountVectorizer()

bow_matrix = vectorizer.fit_transform(documents)

vocabulary = vectorizer.get_feature_names_out()

print("Vocabulary:")
print(vocabulary)

print("\nBag of Words Matrix:")
print(bow_matrix.toarray())

Vocabulary:
['artificial' 'intelligence' 'is' 'learning' 'machine' 'powerful' 'useful']

Bag of Words Matrix:
[[0 0 1 1 1 0 1]
 [0 0 1 1 1 1 0]
 [1 1 1 0 0 0 1]]


In [3]:
import pandas as pd

bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vocabulary
)

print(bow_df)

   artificial  intelligence  is  learning  machine  powerful  useful
0           0             0   1         1        1         0       1
1           0             0   1         1        1         1       0
2           1             1   1         0        0         0       1


In [4]:
# 3. TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "machine learning is useful",
    "machine learning is powerful",
    "artificial intelligence is useful"
]

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(documents)

vocabulary = vectorizer.get_feature_names_out()

print("Vocabulary:")
print(vocabulary)

print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())

Vocabulary:
['artificial' 'intelligence' 'is' 'learning' 'machine' 'powerful' 'useful']

TF-IDF Matrix:
[[0.         0.         0.40912286 0.52682017 0.52682017 0.
  0.52682017]
 [0.         0.         0.37311881 0.4804584  0.4804584  0.63174505
  0.        ]
 [0.5844829  0.5844829  0.34520502 0.         0.         0.
  0.44451431]]


In [5]:
import pandas as pd

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vocabulary
)

print(tfidf_df.round(3))

   artificial  intelligence     is  learning  machine  powerful  useful
0       0.000         0.000  0.409     0.527    0.527     0.000   0.527
1       0.000         0.000  0.373     0.480    0.480     0.632   0.000
2       0.584         0.584  0.345     0.000    0.000     0.000   0.445


In [6]:
!pip install -q gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 49.1 MB/s eta 0:00:00


In [7]:
# 4. WORD2VEC

from gensim.models import Word2Vec

sentences = [
    ["machine", "learning", "is", "useful"],
    ["machine", "learning", "is", "powerful"],
    ["artificial", "intelligence", "is", "useful"],
    ["deep", "learning", "is", "powerful"],
    ["machine", "learning", "uses", "algorithms"],
    ["deep", "learning", "uses", "neural", "networks"]
]

model = Word2Vec(
    sentences=sentences,
    vector_size=50,
    window=3,
    min_count=1,
    sg=1,          # 1 = Skip-gram
    workers=1,
    epochs=100
)

word = "learning"

print(f"Vector for '{word}':")
print(model.wv[word])

print("\nVector size:")
print(len(model.wv[word]))

Vector for 'learning':
[-1.1242982e-03  4.9305119e-04  1.0246474e-02  1.8039862e-02
 -1.8672276e-02 -1.4274492e-02  1.3035284e-02  1.7992085e-02
 -1.0107849e-02 -7.5932341e-03  1.4831991e-02 -3.0621279e-03
 -9.0636257e-03  1.3005170e-02 -9.6864458e-03 -3.6651404e-03
  5.8599804e-03  2.0333049e-03 -1.6701091e-02 -1.8930625e-02
  1.4638886e-02  1.0168064e-02  1.3671765e-02  1.6513475e-03
  1.2686197e-02 -6.7945672e-03 -1.9081193e-03  1.1625796e-02
 -1.5064811e-02 -7.9138344e-03 -1.5051390e-02 -1.9453085e-03
  1.9144170e-02 -1.4782202e-02 -4.7010323e-03 -3.9043529e-03
  1.6297709e-02 -1.1878777e-02  1.6514476e-05 -9.5012216e-03
 -1.9157950e-02  1.0046831e-02 -1.7577892e-02 -8.8597657e-03
  7.9617050e-05 -5.7179417e-04 -1.5320022e-02  1.9211505e-02
  9.9566625e-03  1.8484233e-02]

Vector size:
50


In [8]:
similarity = model.wv.similarity("machine", "learning")

print("Similarity between 'machine' and 'learning':")
print(similarity)

Similarity between 'machine' and 'learning':
0.12775913
